version: '3'
services:
  influxdb:
    image: influxdb:2
    restart: always
    network_mode: "host"
    volumes:
      - /opt/influxdb/data:/var/lib/influxdb2
      - /opt/influxdb/config:/etc/influxdb2
