version: "3"
services:
  telegraf:
    image: telegraf
    restart: always
    network_mode: "host"
    cap_add:
      - CAP_NET_RAW
    command:
      - "--config-directory"
      - "/etc/telegraf"
    volumes:
      - /etc/telegraf:/etc/telegraf
