version: '3'
services:
  server:
    image: xhofe/alist:main
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=33
      - PGID=33
      - UMASK=022
    volumes:
      - /data/alist:/opt/alist/data
      - /data/downloads:/opt/alist/data/local
