version: '3'
services:
  bitwarden:
    image: vaultwarden/server
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
      - "3011:80"
      - "3012:3012"
    volumes:
      - /opt/bitwarden:/data
