version: '3'
services:
  bitwarden:
    image: vaultwarden/server
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
      - "127.0.0.1:3011:80"
      - "127.0.0.1:3012:3012"
    volumes:
      - /opt/bitwarden:/data
