version: '3'
services:
  nginx:
    image: nginx:mainline
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/ssl/openssl.cnf:/etc/ssl/openssl.cnf
      - /etc/gai.conf:/etc/gai.conf
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /var/ssl:/var/ssl
      - /var/log/nginx:/var/log/nginx
      - /usr/share/nginx/html:/usr/share/nginx/html
