version: "3"
services:
  striling-pdf:
    image: frooodle/s-pdf
    restart: always
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SYSTEM_ROOTURIPATH=/${SYSTEM_ROOTURIPATH}
    volumes:
      - /usr/share/tessdata:/usr/share/tessdata
      - /etc/striling-pdf:/configs
      - /var/log/striling-pdf:/logs
    ports:
      - "4728:8080"
