version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:debian
    restart: always
    network_mode: "host"
    user: ":33"
    volumes:
      - /etc/gai.conf:/etc/gai.conf:ro
      - /etc/kuma:/etc/kuma
      - /var/kuma:/app/data
