version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:debian
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/gai.conf:/etc/gai.conf:ro
      - /etc/kuma:/etc/kuma
      - /var/kuma:/app/data
