version: '3.0'
services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    restart: always
    environment:
      - TZ=Asia/Singapore
    volumes:
      - /opt/wallos/db:/var/www/html/db
      - /opt/wallos/logos:/var/www/html/images/uploads/logos
    ports:
      - "127.0.0.1:8282:80"
