version: '3'
services:
  server:
    image: headscale/headscale:0.22.3
    user: "0:9418"
    restart: always
    network_mode: "host"
    volumes:
      - /etc/headscale:/etc/headscale
      - /var/run/headscale:/var/run/headscale
      - /var/lib/headscale:/var/lib/headscale
    command:
      - headscale
      - serve
